required = ["github.com/golang/protobuf/protoc-gen-go"]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.6"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"
